theme: jekyll-theme-tactile
title: ['Totally Information: Development Hub']
description: [Development Information website for Totally Information]

plugins:
  - jekyll-sitemap

collections:
  nr_qa:
    output: true
    permalink: /:collection/:name
    title: 'Node-RED Questions and Answers'
    descriptions: 'Node-RED is a flow-based (visual) programming tool. These pages have some information that may be currently missing from the documentaiton.'
  github_pages:
    output: true
    permalink: /:collection/:name
    title: 'GitHub Pages and Jekyll/Liquid'
    description: 'Hints and tips on using Jekyll for publishing to GitHub Pages.'

defaults:
  - scope:
      path: ""
      type: nr_qa
    values:
      layout: default
      comments: true
  - scope:
      path: ""
      type: github_pages
    values:
      layout: default
      comments: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      comments: false
