#theme: jekyll-theme-tactile
# https://github.com/jekyll/minima

theme: minima
remote-theme: minima
title: 'Totally Information: Development Hub'
# Start with > to ignore newlines until next something:
description: 'Development Information website for Totally Information'
author: Julian Knight
email: gh@totallyinformation.com
linkedin_username: julianknight2
twitter_username: knightnet
github_username: TotallyInformation
google_analytics: UA-113864195-1
rss: true

# Custom meta - if true, output some debug data
ti_debug: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# Must include the index page for folders e.g. _collection-name/index.md, don't include leading slash.
header_pages:
  - _nr-qa/index.md
  - vscode/index.md
  - _github-pages/index.md

disqus:
  shortname: 'totally-information-development-hub'

plugins:
  - jekyll-sitemap

collections:
  nr-qa:
    output: true
    permalink: /:collection/:name
    title: 'Node-RED QA'
    descriptions: >
        Node-RED Questions and Answers

        Node-RED is a flow-based (visual) programming tool. These pages have some information that may be currently missing from the documentation.
  github-pages:
    title: 'GitHub Pages and Jekyll/Liquid'
    description: 'Hints and tips on using Jekyll for publishing to GitHub Pages.'
    ymlMeta: This is some metadata from the config file
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: nr-qa
    values:
      layout: page
      comments: true
      category: Node-RED
      tags:
        - Node.JS
        - JavaScript
  - scope:
      path: ""
      type: GitHub-Pages
    values:
      layout: page
      comments: true
      category: github-pages
      tags:
        - Jekyll
        - HTML
  - scope:
      path: "vscode"
    values:
      layout: page
      comments: true
      category: VSCode
      title: Microsoft Visual Studio Code Hints and Information



