theme: jekyll-theme-tactile
title: ['Totally Information: Development Hub']
description: [Development Information website for Totally Information]

plugins:
  - jekyll-sitemap

collections:
  nr_qa:
    output: true
    permalink: /:collection/:name
