theme: jekyll-theme-tactile
title: ['Totally Information: Development Hub']
description: [Development Information website for Totally Information]

plugins:
  - jekyll-sitemap

collections:
  nr_qa:
    output: true
    permalink: /:collection/:name
    title: 'Node-RED Questions and Answers'

defaults:
  - scope:
      path: ""
      type: nr_qa
    values:
      layout: default
      comments: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
      comments: false
